SharedData = {}

SharedData.Weapons = {
    WEAPON_LASSO = {
        Name        = "Lasso",
        Desc        = "Se consume cuando atas a alguien, el reforzado tiene uso ilimitado para atar",
        AttachPoint = "",             -- TODO add attach point
        HashName    = "WEAPON_LASSO", -- DONT TOUCH
        Weight      = 0.50,           -- 50 kg
    },
    WEAPON_LASSO_REINFORCED = {
        Name        = "Lasso Reforzado",
        Desc        = "Sin límite para atar",
        AttachPoint = "",
        HashName    = "WEAPON_LASSO_REINFORCED",
        Weight      = 0.55,
    },
    WEAPON_MELEE_KNIFE = {
        Name = "Cuchillo",
        Desc = "Cuchillo utilizado principalmente para despellejar animales",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE",
        Weight = 0.33,
    },
    WEAPON_MELEE_KNIFE_RUSTIC = {
        Name = "Cuchillo Rústico",
        Desc = "cuchillo de aspecto antiguo, ¿podría seguir siendo útil?",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE_RUSTIC",
        Weight = 0.40,
    },
    WEAPON_MELEE_KNIFE_HORROR = {
        Name = "Cuchillo Horror",
        Desc = "Este cuchillo fue utilizado para hacer muchas cosas desagradables",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE_HORROR",
        Weight = 0.40,
    },
    WEAPON_MELEE_KNIFE_CIVIL_WAR = {
        Name = "Cuchillo Guerra Civil",
        Desc = "Un cuchillo con mucha historia",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE_CIVIL_WAR",
        Weight = 0.45,
    },
    WEAPON_MELEE_KNIFE_JAWBONE = {
        Name = "Cuchillo Mandíbula",
        Desc = "Un cuchillo hecho de huesos antiguos",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE_JAWBONE",
        Weight = 0.37,
    },
    WEAPON_MELEE_KNIFE_MINER = {
        Name = "Cuchillo Minero",
        Desc = "El mejor amigo del minero",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE_MINER",
        Weight = 0.40,
    },
    WEAPON_MELEE_KNIFE_VAMPIRE = {
        Name = "Cuchillo Vampiro",
        Desc = "No pueden ser reales...",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE_VAMPIRE",
        Weight = 0.39,
    },
    WEAPON_MELEE_CLEAVER = {
        Name = "Cuchilla",
        Desc = "De aspecto aterrador pero útil",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_CLEAVER",
        Weight = 0.73,
    },
    WEAPON_MELEE_HATCHET = {
        Name = "Hacha",
        Desc = "Un trozo de madera con una hoja",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_HATCHET",
        Weight = 1.05,
    },
    WEAPON_MELEE_HATCHET_DOUBLE_BIT = {
        Name = "Hacha Doble Filo",
        Desc = "Un trozo de madera con el doble de hoja",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_HATCHET_DOUBLE_BIT",
        Weight = 1.15,
    },
    WEAPON_MELEE_HATCHET_HEWING = {
        Name = "Hacha de Tala",
        Desc = "Algunos dicen que esta hacha es mágica",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_HATCHET_HEWING",
        Weight = 1.10,
    },
    WEAPON_MELEE_HATCHET_HUNTER = {
        Name = "Hacha Cazador",
        Desc = "El mejor amigo de un cazador",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_HATCHET_HUNTER",
        Weight = 1.15,
    },
    WEAPON_MELEE_HATCHET_VIKING = {
        Name = "Hacha Vikinga",
        Desc = "Huele a pescado y sal",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_HATCHET_VIKING",
        Weight = 1.20,
    },
    WEAPON_THROWN_TOMAHAWK = {
        Name = "Tomahawk",
        Desc = "Un arma digna de un guerrero",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_TOMAHAWK",
        Weight = 1.30,
    },
    WEAPON_THROWN_TOMAHAWK_ANCIENT = {
        Name = "Tomahawk Antiguo",
        Desc = "Este es Antiguo",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_TOMAHAWK_ANCIENT",
        Weight = 1.50,
    },
    WEAPON_THROWN_THROWING_KNIVES = {
        Name = "Cuchillos Arrojadizos",
        Desc = "A la gente le encanta jugar con estos",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_THROWING_KNIVES",
        Weight = 1.05,
    },
    WEAPON_MELEE_MACHETE = {
        Name = "Machete",
        Desc = "Útil en la jungla",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_MACHETE",
        Weight = 1.3,
    },
    WEAPON_BOW = {
        Name = "Arco",
        Desc = "Un arma simple pero efectiva",
        AttachPoint = "",
        HashName = "WEAPON_BOW",
        Weight = 0.85,
    },
    WEAPON_PISTOL_SEMIAUTO = {
        Name = "Pistola Semiautomática",
        Desc = "pistola de repetición de una sola cámara",
        AttachPoint = "",
        HashName = 'WEAPON_PISTOL_SEMIAUTO',
        Weight = 1.18,
    },
    WEAPON_PISTOL_MAUSER = {
        Name = "Pistola Mauser",
        Desc = "pistola semiautomática que fue originalmente producida por el fabricante alemán de armas Mauser",
        AttachPoint = "",
        HashName = "WEAPON_PISTOL_MAUSER",
        Weight = 1.13,
    },
    WEAPON_PISTOL_VOLCANIC = {
        Name = "Pistola Volcánica",
        Desc = "una versión mejorada de la munición Rocket Ball",
        AttachPoint = "",
        HashName = "WEAPON_PISTOL_VOLCANIC",
        Weight = 1.10,
    },
    WEAPON_PISTOL_M1899 = {
        Name = "Pistola M1899",
        Desc = "su munición cargada en el cargador permite una recarga rápida",
        AttachPoint = "",
        HashName = "WEAPON_PISTOL_M1899",
        Weight = 1.15,
    },
    WEAPON_REVOLVER_SCHOFIELD = {
        Name = "Revolver Schofield",
        Desc = "revólver de acción simple, que dispara cartuchos y se abre por la parte superior",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_SCHOFIELD",
        Weight = 1.30,
    },
    WEAPON_REVOLVER_NAVY = {
        Name = "Revólver Navy",
        Desc = "revólver de percusión diseñado por Samuel Colt",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_NAVY",
        Weight = 1.20,
    },
    WEAPON_REVOLVER_NAVY_CROSSOVER = {
        Name = "Revólver Navy Crossover",
        Desc = "un revólver que también es una escopeta",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_NAVY_CROSSOVER",
        Weight = 1.25,
    },
    WEAPON_REVOLVER_LEMAT = {
        Name = "Revólver LeMat",
        Desc = "un revólver que también es una escopeta",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_LEMAT",
        Weight = 1.86,
    },
    WEAPON_REVOLVER_DOUBLEACTION = {
        Name = "Revólver Doble Acción",
        Desc = "tiene un gatillo que tanto amartilla el martillo como lo libera en un solo tirón",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_DOUBLEACTION",
        Weight = 0.94,
    },
    WEAPON_REVOLVER_CATTLEMAN = {
        Name = "Revólver Cattleman",
        Desc = "El mejor amigo de un vaquero",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_CATTLEMAN",
        Weight = 1.04,
    },
    WEAPON_REVOLVER_CATTLEMAN_MEXICAN = {
        Name = "Revólver Cattleman Mexicano",
        Desc = "un sabor diferente",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_CATTLEMAN_MEXICAN",
        Weight = 1.04,
    },
    WEAPON_RIFLE_VARMINT = {
        Name = "Rifle Varmint",
        Desc = "Un rifle útil para cazar bichos",
        AttachPoint = "",
        HashName = "WEAPON_RIFLE_VARMINT",
        Weight = 3.80,
    },
    WEAPON_REPEATER_WINCHESTER = {
        Name = "Winchester Repetidor",
        Desc = "rifles de repetición de acción de palanca fabricados por la Winchester Repeating Arms Company",
        AttachPoint = "",
        HashName = "WEAPON_REPEATER_WINCHESTER",
        Weight = 4.30,
    },
    WEAPON_REPEATER_HENRY = {
        Name = "Henry Repetidor",
        Desc = "rifle de repetición con cargador tubular de acción de palanca",
        AttachPoint = "",
        HashName = "WEAPON_REPEATER_HENRY",
        Weight = 4.20,
    },
    WEAPON_REPEATER_EVANS = {
        Name = "Evans Repetidor",
        Desc = "un rifle de repetición de acción de palanca diseñado por Warren R. Evans como un rifle de alta capacidad",
        AttachPoint = "",
        HashName = "WEAPON_REPEATER_EVANS",
        Weight = 4.45,
    },
    WEAPON_REPEATER_CARBINE = {
        Name = "Carabina Repetidora",
        Desc =
        "Un rifle de repetición confiable y popular, la Carabina Buck proporciona daño medio y una velocidad de disparo decente",
        AttachPoint = "",
        HashName = "WEAPON_REPEATER_CARBINE",
        Weight = 4.10,
    },
    WEAPON_SNIPERRIFLE_ROLLINGBLOCK = {
        Name = "Rifle Rolling Block",
        Desc = "El Remington Rolling Block es una familia de rifles de retrocarga",
        AttachPoint = "",
        HashName = "WEAPON_SNIPERRIFLE_ROLLINGBLOCK",
        Weight = 4.20,
    },
    WEAPON_SNIPERRIFLE_CARCANO = {
        Name = "Rifle Carcano",
        Desc = "El Carcano es un rifle italiano de cerrojo",
        AttachPoint = "",
        HashName = "WEAPON_SNIPERRIFLE_CARCANO",
        Weight = 3.62,
    },
    WEAPON_RIFLE_SPRINGFIELD = {
        Name = "Rifle Springfield",
        Desc = "Rifle estándar del ejército",
        AttachPoint = "",
        HashName = "WEAPON_RIFLE_SPRINGFIELD",
        Weight = 3.90,
    },
    WEAPON_RIFLE_ELEPHANT = {
        Name = "Rifle Elefante",
        Desc = "Mejor arma para un cazador que busca derribar presas grandes",
        AttachPoint = "",
        HashName = "WEAPON_RIFLE_ELEPHANT",
        Weight = 12.50,
    },
    WEAPON_RIFLE_BOLTACTION = {
        Name = "Rifle de Cerrojo",
        Desc = "acción de arma de fuego manual que se opera manipulando directamente el cerrojo",
        AttachPoint = "",
        HashName = "WEAPON_RIFLE_BOLTACTION",
        Weight = 4.08,
    },
    WEAPON_SHOTGUN_SEMIAUTO = {
        Name = "Escopeta Semiautomática",
        Desc = "una escopeta de repetición con acción semiautomática, capaz de recargar automáticamente un nuevo cartucho",
        AttachPoint = "",
        HashName = "WEAPON_SHOTGUN_SEMIAUTO",
        Weight = 3.53,
    },
    WEAPON_SHOTGUN_SAWEDOFF = {
        Name = "Escopeta Recortada",
        Desc = "escopeta con un cañón más corto",
        AttachPoint = "",
        HashName = "WEAPON_SHOTGUN_SAWEDOFF",
        Weight = 1.90,
    },
    WEAPON_SHOTGUN_REPEATING = {
        Name = "Escopeta Repetidora",
        Desc = "La Escopeta Repetidora Lancaster",
        AttachPoint = "",
        HashName = "WEAPON_SHOTGUN_REPEATING",
        Weight = 3.60,
    },
    WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC = {
        Name = "Escopeta Doble Cañón Exótica",
        Desc = "variante de rareza exótica de la Escopeta Doble Cañón",
        AttachPoint = "",
        HashName = "WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC",
        Weight = 3.71,
    },
    WEAPON_SHOTGUN_PUMP = {
        Name = "Escopeta de Bombeo",
        Desc = "acción de arma de repetición que se opera manualmente moviendo un guardamanos deslizante",
        AttachPoint = "",
        HashName = "WEAPON_SHOTGUN_PUMP",
        Weight = 3.60,
    },
    WEAPON_SHOTGUN_DOUBLEBARREL = {
        Name = "Escopeta Doble Cañón",
        Desc =
        "escopeta de acción de ruptura con dos cañones paralelos, que permite disparar dos tiros simples en rápida sucesión",
        AttachPoint = "",
        HashName = "WEAPON_SHOTGUN_DOUBLEBARREL",
        Weight = 3.65,
    },
    WEAPON_KIT_CAMERA = {
        Name = "Cámara",
        Desc = "la mejor amiga de un periodista",
        AttachPoint = "",
        HashName = "WEAPON_KIT_CAMERA",
        Weight = 0.47,
    },
    WEAPON_KIT_BINOCULARS_IMPROVED = {
        Name = "Binoculares Mejorados",
        Desc = "¡Ve las cosas con claridad!",
        AttachPoint = "",
        HashName = "WEAPON_KIT_BINOCULARS_IMPROVED",
        Weight = 1.50,
    },
    WEAPON_MELEE_KNIFE_TRADER = {
        Name = "Cuchillo Comerciante",
        Desc = "el mejor amigo de un comerciante",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE_TRADER",
        Weight = 0.45,
    },
    WEAPON_KIT_BINOCULARS = {
        Name = "Binoculares",
        Desc = "te permite ver cosas lejanas",
        AttachPoint = "",
        HashName = "WEAPON_KIT_BINOCULARS",
        Weight = 1.45,
    },
    WEAPON_KIT_CAMERA_ADVANCED = {
        Name = "Cámara Avanzada",
        Desc = "una cámara que es ligeramente mejor tecnológicamente",
        AttachPoint = "",
        HashName = "WEAPON_KIT_CAMERA_ADVANCED",
        Weight = 0.55,
    },
    WEAPON_MELEE_LANTERN = {
        Name = "Linterna",
        Desc = "te permite ver mejor en la oscuridad",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_LANTERN",
        Weight = 0.56,
    },
    WEAPON_MELEE_DAVY_LANTERN = {
        Name = "Linterna Davy",
        Desc = "lámpara de seguridad para usar en atmósferas inflamables",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_DAVY_LANTERN",
        Weight = 0.65,
    },
    WEAPON_MELEE_LANTERN_HALLOWEEN = {
        Name = "Linterna de Halloween",
        Desc = "hecha con un cráneo humano real",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_LANTERN_HALLOWEEN",
        Weight = 1.20,
    },
    WEAPON_THROWN_POISONBOTTLE = {
        Name = "Botella de Veneno",
        Desc = "quién sabe qué hay en esta cosa",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_POISONBOTTLE",
        Weight = 0.35,
    },
    WEAPON_KIT_METAL_DETECTOR = {
        Name = "Detector de Metales",
        Desc = "te ayuda a encontrar objetos de valor",
        AttachPoint = "",
        HashName = "WEAPON_KIT_METAL_DETECTOR",
        Weight = 0.45,
    },
    WEAPON_THROWN_DYNAMITE = {
        Name = "Dinamita",
        Desc = "palito explosivo",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_DYNAMITE",
        Weight = 0.19,
    },
    WEAPON_THROWN_MOLOTOV = {
        Name = "Molotov",
        Desc = "el mejor amigo de un incendiario",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_MOLOTOV",
        Weight = 0.45,
    },
    WEAPON_BOW_IMPROVED = {
        Name = "Arco Mejorado",
        Desc = "un arco con mejor precisión",
        AttachPoint = "",
        HashName = "WEAPON_BOW_IMPROVED",
        Weight = 1.10,
    },
    WEAPON_MELEE_MACHETE_COLLECTOR = {
        Name = "Machete Coleccionista",
        Desc = "todo coleccionista necesita uno",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_MACHETE_COLLECTOR",
        Weight = 1.40,
    },
    WEAPON_MELEE_LANTERN_ELECTRIC = {
        Name = "Linterna Eléctrica",
        Desc = "una maravilla de la tecnología",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_LANTERN_ELECTRIC",
        Weight = 0.95,
    },
    WEAPON_MELEE_TORCH = {
        Name = "Antorcha",
        Desc = "tu básico palo en llamas",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_TORCH",
        Weight = 1.50,
    },
    WEAPON_MOONSHINEJUG_MP = {
        Name = "Jarra de Moonshine",
        Desc = "esas son muy divertidas",
        AttachPoint = "",
        HashName = "WEAPON_MOONSHINEJUG_MP",
        Weight = 2.00,
    },
    WEAPON_THROWN_BOLAS = {
        Name = "Bolas",
        Desc = "todo vaquero rudo necesita una",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_BOLAS",
        Weight = 0.55,
    },
    WEAPON_THROWN_BOLAS_HAWKMOTH = {
        Name = "Bolas Halcón Polilla",
        Desc = "una bola con un giro",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_BOLAS_HAWKMOTH",
        Weight = 0.65,
    },
    WEAPON_THROWN_BOLAS_IRONSPIKED = {
        Name = "Bolas con Puntas de Hierro",
        Desc = "una bola más afilada",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_BOLAS_IRONSPIKED",
        Weight = 0.75,
    },
    WEAPON_THROWN_BOLAS_INTERTWINED = {
        Name = "Bolas Entretejidas",
        Desc = "una bola más fuerte",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_BOLAS_INTERTWINED",
        Weight = 0.60,
    },
    WEAPON_FISHINGROD = {
        Name = "Caña de Pescar",
        Desc = "qué mejor que pescar",
        AttachPoint = "",
        HashName = "WEAPON_FISHINGROD",
        Weight = 1.10,
    },
    WEAPON_MACHETE_HORROR = {
        Name = "Machete Horror",
        Desc = "este asusta a la gente",
        AttachPoint = "",
        HashName = "WEAPON_MACHETE_HORROR",
        Weight = 1.40,
    },
    WEAPON_MELEE_HAMMER = {
        Name        = "Martillo",
        Desc        = "¡Martillo de Richards!",
        AttachPoint = "",
        HashName    = "WEAPON_MELEE_HAMMER",
        Weight      = 1.25,
    },
    WEAPON_REVOLVER_DOUBLEACTION_GAMBLER = {
        Name        = "Revólver Doble Acción de Gran Apostador",
        Desc        = "Revólver de doble acción con motivos de apostador grabados en toda el arma",
        AttachPoint = "",
        HashName    = "WEAPON_REVOLVER_DOUBLEACTION_GAMBLER",
        Weight      = 1.05,
    },
}
